# -*- coding: utf-8 -*-
"""Copy of run grpo - nsr integrated of rvr-pres[v3].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11YfTYnNZIQFhQoegsHH62uG3hUtq-3MJ
"""

# Check GPU type
!nvidia-smi --query-gpu=name --format=csv,noheader

# Should output: NVIDIA A100-SXM4-40GB
# If you see Tesla T4, you need Colab Pro!

# Set environment
import os
os.environ['HF_HUB_CACHE'] = '/content/hf_cache'
os.environ['TRANSFORMERS_CACHE'] = '/content/hf_cache'
os.environ['HF_HOME'] = '/content/hf_cache'

print("✓ GPU check complete")

# Install all required packages
!pip install -q torch==2.4.0
!pip install -q transformers==4.47.1
!pip install -q peft==0.14.0
!pip install -q trl==0.12.1
!pip install -q accelerate==1.2.1
!pip install -q deepspeed==0.15.4
!pip install -q datasets==3.1.0
!pip install -q qwen-vl-utils==0.0.8
!pip install -q wandb
!pip install -q sentence-transformers
!pip install -q sacrebleu
!pip install -q matplotlib
!pip install -q numpy
!pip install -q pandas
!pip install -q pillow

print("✓ All dependencies installed")

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/potate4/chartrl.git
!git checkout -b nsr-integrated
# %cd chartrl
!pwd

!git pull origin nsr-integrated

# Commented out IPython magic to ensure Python compatibility.
# %cd chartrl

# PyTorch with CUDA 12.4
!pip install -q torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cu124

# Flash Attention 2 (critical - takes ~5 min)
!pip install -q flash-attn==2.7.4.post1 --no-build-isolation

# Core libraries
!pip install -q trl==0.12.0 transformers==4.53.1 datasets==3.6.0 accelerate==1.7.0 deepspeed==0.15.3 peft==0.15.2

# Additional dependencies
!pip install -q qwen-vl-utils==0.0.11 wandb==0.20.1 sentence-transformers sacrebleu scipy scikit-image Pillow==10.4.0

!pip install -r reqs2.txt

!pip install -U trl

# Create __init__.py files for Python modules
!touch trainers/__init__.py
!touch evaluation/__init__.py

# Verify structure
!ls -la trainers/
!ls -la evaluation/

print("✓ Module structure created")

!python -c "import torch; print(f'PyTorch: {torch.__version__}'); print(f'CUDA: {torch.cuda.is_available()}')"
!python -c "import flash_attn; print(f'Flash Attention: {flash_attn.__version__}')"
!python -c "from trl import GRPOTrainer; print('TRL: OK')"

from google.colab import output
output.enable_custom_widget_manager()

from huggingface_hub import login
login()

# Commented out IPython magic to ensure Python compatibility.
# %cd chartrl

# Create DeepSpeed Zero-3 configuration
deepspeed_config = """compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
main_process_port: 29501
"""

with open('deepspeed_zero3.yaml', 'w') as f:
    f.write(deepspeed_config)

print("✓ DeepSpeed config created")

import wandb

# Login to W&B for experiment tracking
wandb.login()

# Or to disable W&B:
# import os
# os.environ['WANDB_MODE'] = 'disabled'

print("✓ Weights & Biases configured")

!wandb login

import os
os.environ['WANDB_MODE'] = 'disabled'

import random

import wandb

# Start a new wandb run to track this script.
run = wandb.init(
    # Set the wandb entity where your project will be logged (generally your team name).
    entity="chartrl",
    # Set the wandb project where this run will be logged.
    project="chartrl",
    # Track hyperparameters and run metadata.
    config={
    },
)

from google.colab import drive

# Mount Google Drive for checkpoint backup
drive.mount('/content/drive')

# Create backup directory
!mkdir -p /content/drive/MyDrive/chartrl_checkpoints

print("✓ Google Drive mounted")

import time
import shutil
import threading
import os

def backup_checkpoints():
    """Auto-backup checkpoints to Google Drive every hour"""
    while True:
        time.sleep(1800)  # Every 0.5 hour
        if os.path.exists('grpo-start-ckpts'):
            print(f"\n[{time.strftime('%H:%M:%S')}] Backing up checkpoints to Drive...")
            try:
                shutil.copytree(
                    'grpo-start-ckpts',
                    '/content/drive/MyDrive/chartrl_checkpoints/grpo-start-ckpts-1000-4',
                    dirs_exist_ok=True
                )
                print(f"[{time.strftime('%H:%M:%S')}] ✓ Backup complete")
            except Exception as e:
                print(f"[{time.strftime('%H:%M:%S')}] Backup failed: {e}")

# Start backup thread
backup_thread = threading.Thread(target=backup_checkpoints, daemon=True)
backup_thread.start()

print("✓ Auto-backup started (saves every hour)")

!mkdir -p /content/hf_cache

# Verify files were updated (cache paths should show /content/hf_cache)
!grep "cache_dir = '/content/hf_cache'" main.py
!grep "cache_dir = '/content/hf_cache'" dataset_process.py
!grep "num_processes: 1" deepspeed_zero3.yaml

from datasets import load_dataset
import os

cache_dir = '/content/hf_cache'

print("Downloading Chart-RVR GRPO training dataset...")
dataset = load_dataset("sanchit97/chart-rvr-grpo-train", cache_dir=cache_dir)

print(f"\nDataset info: {dataset}")
print(f"Number of samples: {len(dataset['train'])}")

# Save to disk for faster loading
save_path = f"{cache_dir}/grpo-chartrvr-train"
dataset.save_to_disk(save_path)
print(f"\n✓ Dataset saved to: {save_path}")

# Verify
assert os.path.exists(save_path), "Dataset save failed!"
print("\n✓ Verification passed")

# Inspect sample
sample = dataset['train'][0]
print("\n=== Sample Data ===")
print(f"Query: {sample['query'][:100]}...")
print(f"Label: {sample['label']}")
print(f"Chart Type: {sample['chart_type']}")
print(f"Has table: {sample['table'] is not None}")
print(f"Has reasoning: {len(sample['reasoning'])} chars")

from datasets import load_dataset
import os
dataset = load_dataset(path="/content/hf_cache/grpo-chartrvr-train")

# Inspect sample
sample = dataset['train'][0]
print("\n=== Sample Data ===")
print(f"Query: {sample['query'][:100]}...")
print(f"Label: {sample['label']}")
print(f"Chart Type: {sample['chart_type']}")
print(f"Has table: {sample['table'] is not None}")
print(f"Has reasoning: {len(sample['reasoning'])} chars")

# Check dataset
!ls -lh /content/hf_cache/grpo-chartrvr-train/

# Check GPU memory (should be mostly free)
!nvidia-smi

# Check code modifications
!head -n 50 main.py | grep cache_dir



# Commented out IPython magic to ensure Python compatibility.
# %cd chartrl

import os
os.environ['TRANSFORMERS_VERBOSITY'] = 'info'
os.environ['ACCELERATE_LOG_LEVEL'] = 'info'

!python main.py \
  --mode grpo \
  --vlm-name qwen2-5-3b \
  --dataset-name evochart \
  --seed 2026



# Full training (34K samples, 4 epochs, ~14-16 hours)
!accelerate launch --config_file=deepspeed_zero3.yaml main.py \
  --mode grpo \
  --vlm-name qwen2-5-3b \
  --dataset-name evochart \
  --seed 2025

# Commented out IPython magic to ensure Python compatibility.
# %env WANDB_MODE=disabled

!pip install -U trl

import os

# Unset the environment variable (if set)
if 'WANDB_API_KEY' in os.environ:
    del os.environ['WANDB_API_KEY']

!pip install undecorated

!pip freeze

!accelerate launch --config_file=deepspeed_zero3.yaml main.py \
  --mode grpo \
  --vlm-name qwen2-5-3b \
  --dataset-name evochart \
  --seed 2025 \
  --subset-size 1000 \
  --num-epochs 1 \
  --num-generations 2

from google.colab import output
output.enable_custom_widget_manager()

print("="*80)
print("TRAINING 1/2: GRPO BASELINE")
print("="*80)

!accelerate launch --config_file=deepspeed_zero3.yaml main.py \
  --mode grpo \
  --vlm-name qwen2-5-3b \
  --dataset-name evochart \
  --seed 2025 \
  --subset-size 100 \
  --num-epochs 1 \
  --num-generations 2 \
  --batch-size 2 \
  2>&1 | tee poc_grpo.log

print("\n" + "="*80)
print("✓ GRPO training complete")
print("="*80)

print("="*80)
print("TRAINING 2/2: NSR (NEGATIVE SAMPLE REINFORCEMENT) - FIXED")
print("="*80)

!accelerate launch --config_file=deepspeed_zero3.yaml main.py \
  --mode nsr \
  --vlm-name qwen2-5-3b \
  --dataset-name evochart \
  --seed 2025 \
  --subset-size 100 \
  --num-epochs 1 \
  --num-generations 4 \
  --batch-size 2 \
  --reward-threshold 5.0 \
  2>&1 | tee nsr_fixed_2.log

print("\n" + "="*80)
print("✓ NSR training complete")
print("="*80)

#  Generate convergence plots
!python monitor_training.py \
  --checkpoint-dir /content/drive/MyDrive/chartrl_checkpoints/grpo-start-ckpts/qwen2-5-3b-prm-large-train-v2-2026/checkpoint-50\
  --output-dir poc_plots

# Display plots
from IPython.display import Image, display

print("\n" + "="*80)
print("Training Convergence Plots")
print("="*80)

plots = [
    ("Training Loss", "poc_plots/training_loss.png"),
    ("Learning Rate", "poc_plots/learning_rate.png"),
    ("Gradient Norm", "poc_plots/gradient_norm.png"),
]

for title, path in plots:
    if os.path.exists(path):
        print(f"\n{title}:")
        display(Image(path))

/content/drive/MyDrive/chartrl_checkpoints/grpo-start-ckpts/qwen2-5-3b-prm-large-train-v2-nsr-2026/checkpoint-100

#  Generate convergence plots
!python monitor_training.py \
  --checkpoint-dir /content/drive/MyDrive/chartrl_checkpoints/grpo-start-ckpts/qwen2-5-3b-prm-large-train-v2-nsr-2026/checkpoint-100 \
  --output-dir poc_plots

# Display plots
from IPython.display import Image, display

print("\n" + "="*80)
print("Training Convergence Plots")
print("="*80)

plots = [
    ("Training Loss", "poc_plots/training_loss.png"),
    ("Learning Rate", "poc_plots/learning_rate.png"),
    ("Gradient Norm", "poc_plots/gradient_norm.png"),
]

for title, path in plots:
    if os.path.exists(path):
        print(f"\n{title}:")
        display(Image(path))

!zip -r 50_sample_run.zip /content/chartrl

from google.colab import files
files.download("50_sample_run.zip")

print("="*80)
print("TRAINING 1/2: GRPO BASELINE")
print("="*80)

!accelerate launch --config_file=deepspeed_zero3.yaml main.py \
  --mode grpo \
  --vlm-name qwen2-5-3b \
  --dataset-name evochart \
  --seed 2026 \
  --subset-size 1000 \
  --num-epochs 1 \
  --num-generations 4 \
  --batch-size 2 \
  2>&1 | tee poc_grpo_1000.log

print("\n" + "="*80)
print("✓ GRPO training complete")
print("="*80)

from google.colab import drive
drive.mount('/content/drive')