# -*- coding: utf-8 -*-
"""hcpc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQzcRTZKlWkMe4Kkbj9oJyKRCh9eRk_a
"""

from google.colab import drive
drive.mount('/content/drive')

!git stash

import os

# Configure your repository (update these)
REPO_URL = "https://github.com/potate4/chartrl.git"  # Your repo URL
BRANCH = "feat/hcpc-fixes"  # or your branch name

# Working directories
WORK_DIR = "/content/chartrl"
DRIVE_BACKUP_DIR = "/content/drive/MyDrive/hcpc_rlvr_checkpoints"

# Clone or pull latest
if os.path.exists(WORK_DIR):
    print("Repository exists, pulling latest...")
    os.chdir(WORK_DIR)
    !git pull origin {BRANCH}
else:
    print("Cloning repository...")
    !git clone -b {BRANCH} {REPO_URL} {WORK_DIR}
    os.chdir(WORK_DIR)

# Create backup directory on Drive
os.makedirs(DRIVE_BACKUP_DIR, exist_ok=True)
print(f"Backup directory: {DRIVE_BACKUP_DIR}")

# Change to app directory
os.chdir(f"{WORK_DIR}/app")
print(f"Working directory: {os.getcwd()}")

# Install required packages
!pip install -q torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install -q transformers>=4.45.0 accelerate>=0.34.0 peft>=0.13.0
!pip install -q datasets pillow tqdm wandb
!pip install -q sentence-transformers deepspeed bitsandbytes
!pip install -q qwen-vl-utils
!pip install -q trl>=0.12.0
!pip install -U trl

# Verify GPU
import torch
print(f"GPU Available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

import threading
import time
import shutil
from datetime import datetime
from pathlib import Path

class DriveBackupManager:
    """Automatically backs up checkpoints to Google Drive."""

    def __init__(
        self,
        source_dir: str = "./outputs",
        backup_dir: str = "/content/drive/MyDrive/hcpc_rlvr_checkpoints",
        interval_minutes: int = 5,
    ):
        self.source_dir = Path(source_dir)
        self.backup_dir = Path(backup_dir)
        self.interval = interval_minutes * 60  # Convert to seconds
        self.running = False
        self.thread = None
        self.last_backup = None
        self.backup_count = 0

    def _get_checkpoint_dirs(self):
        """Find all checkpoint directories."""
        checkpoints = []
        if self.source_dir.exists():
            for exp_dir in self.source_dir.iterdir():
                if exp_dir.is_dir():
                    for run_dir in exp_dir.glob("run_*"):
                        ckpt_dir = run_dir / "checkpoints"
                        if ckpt_dir.exists():
                            checkpoints.append(ckpt_dir)
        return checkpoints

    def _backup_once(self):
        """Perform a single backup."""
        checkpoint_dirs = self._get_checkpoint_dirs()

        if not checkpoint_dirs:
            return False

        for ckpt_dir in checkpoint_dirs:
            # Get relative path from outputs
            rel_path = ckpt_dir.relative_to(self.source_dir)
            dest_dir = self.backup_dir / rel_path

            # Copy new checkpoint files
            for ckpt in ckpt_dir.iterdir():
                if ckpt.is_dir() and ckpt.name.startswith("step_"):
                    dest_ckpt = dest_dir / ckpt.name
                    if not dest_ckpt.exists():
                        print(f"[Backup] Copying {ckpt.name} to Drive...")
                        shutil.copytree(ckpt, dest_ckpt)
                        self.backup_count += 1

            # Also copy config and metrics
            run_dir = ckpt_dir.parent
            for file in ["config.json", "metrics.jsonl"]:
                src_file = run_dir / file
                if src_file.exists():
                    dest_file = dest_dir.parent / file
                    dest_file.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(src_file, dest_file)

        self.last_backup = datetime.now()
        return True

    def _backup_loop(self):
        """Background backup loop."""
        while self.running:
            try:
                self._backup_once()
            except Exception as e:
                print(f"[Backup] Error: {e}")
            time.sleep(self.interval)

    def start(self):
        """Start automatic backup."""
        if self.running:
            print("[Backup] Already running")
            return

        self.running = True
        self.thread = threading.Thread(target=self._backup_loop, daemon=True)
        self.thread.start()
        print(f"[Backup] Started - backing up every {self.interval // 60} minutes")
        print(f"[Backup] Source: {self.source_dir}")
        print(f"[Backup] Destination: {self.backup_dir}")

    def stop(self):
        """Stop automatic backup."""
        self.running = False
        if self.thread:
            self.thread.join(timeout=5)
        print(f"[Backup] Stopped - {self.backup_count} checkpoints backed up")

    def backup_now(self):
        """Trigger immediate backup."""
        print("[Backup] Manual backup triggered...")
        success = self._backup_once()
        if success:
            print(f"[Backup] Complete at {self.last_backup}")
        else:
            print("[Backup] No checkpoints found yet")

    def status(self):
        """Print backup status."""
        print(f"[Backup] Running: {self.running}")
        print(f"[Backup] Last backup: {self.last_backup}")
        print(f"[Backup] Total backed up: {self.backup_count}")


# Create and start backup manager
backup_manager = DriveBackupManager(
    source_dir="./outputs",
    backup_dir=DRIVE_BACKUP_DIR,
    interval_minutes=5,  # Backup every 5 minutes
)
backup_manager.start()

import shutil
from pathlib import Path

def restore_from_drive(
    drive_dir: str = "/content/drive/MyDrive/hcpc_rlvr_checkpoints",
    local_dir: str = "./outputs",
):
    """Restore checkpoints from Google Drive."""
    drive_path = Path(drive_dir)
    local_path = Path(local_dir)

    if not drive_path.exists():
        print("No backup found on Drive")
        return

    # Find all experiments in backup
    for exp_dir in drive_path.iterdir():
        if exp_dir.is_dir():
            dest_exp = local_path / exp_dir.name

            for run_dir in exp_dir.glob("run_*"):
                dest_run = dest_exp / run_dir.name

                if dest_run.exists():
                    print(f"Skipping {run_dir.name} (already exists)")
                    continue

                print(f"Restoring {exp_dir.name}/{run_dir.name}...")
                shutil.copytree(run_dir, dest_run)

    print("Restore complete!")

# Uncomment to restore:
restore_from_drive()

import sys
sys.path.insert(0, '.')

# Test imports
from configs.experiment import EXPERIMENTS, list_experiments
from data import load_training_dataset
from models import load_model_for_training

print("All imports successful!")
print()
list_experiments()

!python scripts/train.py \
    --experiment grpo_baseline \
    --subset-size 10 \
    --num-epochs 1 \
    --no-wandb

!python scripts/train.py \
    --experiment grpo_baseline \
    --subset-size 1000 \
    --num-epochs 2 \
    --no-wandb \
    --batch-size 1 \
    --num-generations 4

!python scripts/train.py \
    --experiment grpo_hcpc \
    --subset-size 1000 \
    --num-epochs 2 \
    --no-wandb \
    --batch-size 2 \
    --num-generations 4

!nvidia-smi --query-gpu=name --format=csv,noheader

!python app/scripts/evaluate.py \
  --checkpoint /content/chartrl/app/outputs/grpo_baseline/run_20260209_054445 \
  --id-dataset chartqa \
  --ood-dataset evochart \
  --num-samples 4


  python scripts/eval_run.py --dataset evochart --subset 500 --num-samples 4


  python scripts/train.py \
    --resume-from /home/cse/Desktop/sumaiya223/chartrl/app/outputs/grpo_hcpc/run_20260219_191830/trl_output/checkpoint-850 \
    --experiment grpo_hcpc \
    --subset-size 1000 \
    --num-epochs 2 \
    --no-wandb \
    --batch-size 1 \
    --num-generations 4 



    python scripts/train.py \
    --resume-from /home/cse/Desktop/sumaiya223/chartrl/app/outputs/grpo_hcpc/run_20260219_191830/trl_output/checkpoint-850 \
    --experiment grpo_hcpc \
    --subset-size 1000 \
    --num-epochs 2 \
    --no-wandb \
    --batch-size 1 \
    --num-generations 4 




python app/scripts/train.py \
  --experiment grpo_hcpc \
  --subset-size 1000 \
  --num-epochs 2 \
  --no-wandb \
  --batch-size 2 \
  --num-generations 4
